# Generated by Django 4.1.6 on 2023-02-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supera_ecommece', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='n_Insricao',
            new_name='n_Inscricao',
        ),
    ]
