# Generated by Django 4.1.6 on 2023-02-10 14:13

import Supera_ecommece.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supera_ecommece', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(blank=True, upload_to=Supera_ecommece.models.photos),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='foto',
            field=models.ImageField(blank=True, upload_to=Supera_ecommece.models.photos),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='image',
            field=models.ImageField(blank=True, upload_to=Supera_ecommece.models.photos),
        ),
    ]
